---
before:
  hooks:
    - go mod tidy

builds:
  - id: webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./
    binary: webhook

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'

dockers:
  - image_templates:
      - 'ghcr.io/nukleros/pod-security-webhook:v{{ .Version }}'
      - 'ghcr.io/nukleros/pod-security-webhook:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=VERSION={{ .Version }}"
      - "--platform=linux/amd64"
